# Generated by Django 5.2.17 on 2026-09-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_timestamp_auto_now_price_not_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': 'asset', 'verbose_name_plural': 'assets'},
        ),
        migrations.AlterModelOptions(
            name='userassets',
            options={'verbose_name': 'monitored asset', 'verbose_name_plural': 'monitored assets'},
        ),
    ]
